import * as THREE from 'three';
import {OrbitControls} from './vendor/three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from './vendor/three/examples/jsm/loaders/GLTFLoader.js';
import {DRACOLoader} from './vendor/three/examples/jsm/loaders/DRACOLoader.js';
const shots=[[[0,2.95,3.9],[0,2.85,.2]],[[.06,3.28,1.65],[0,3.22,.22]],[[-2,3.2,4.4],[0,2.85,.1]],[[2.6,3.4,4.8],[0,2.8,0]],[[0,3.3,-3.6],[0,2.9,0]],[[1,3.25,2],[0,3.15,.1]],[[0,4.5,7.8],[0,2.9,-.5]]];
const palettes={sakura:['#ff81bb','#bb8cff'],aurora:['#89cfff','#ba97ff'],gold:['#ffe5ab','#ffabbd'],night:['#8494c4','#8c79ad']};
export class Stage{
 constructor(host){this.host=host;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#100a19');this.camera=new THREE.PerspectiveCamera(36,1,.02,100);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enabled=false;this.controls.enableDamping=true;this.controls.minDistance=.3;this.controls.maxDistance=30;this.controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};this.renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();document.querySelector('#loading-status').hidden=false;document.querySelector('#load-text').textContent='图形上下文已暂停，请重试';document.querySelector('#retry').hidden=false;});this.scene.add(new THREE.HemisphereLight(0xffdeee,0x493366,1.1));this.motion=true;this.reduced=false;this.time=0;this.frames=0;this.materials=[];this.beams=[];this.tint=new THREE.Color('white');this.targetTint=new THREE.Color('white');this.pivot=new THREE.Group();this.pivot.position.set(0,2.07,.1);this.scene.add(this.pivot);this.quality('auto');new ResizeObserver(()=>{this.resize();this.shot(this.index||0,true);}).observe(host);this.decorate();this.mood('sakura');this.renderer.setAnimationLoop(t=>this.frame(t));}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;this.camera.aspect=w/h;this.camera.clearViewOffset();this.camera.setViewOffset(w,h,-w*(w>800?.22:.13),h*(w>800?0:.16),w,h);this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
 quality(q){this.renderer.setPixelRatio(q==='low'?1:q==='high'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,innerWidth<800?1.25:1.5));this.resize();if(this.particles)this.particles.geometry.setDrawRange(0,q==='low'?65:220);}
 async load(progress){const draco=new DRACOLoader().setDecoderPath('./vendor/three/examples/jsm/libs/draco/gltf/');try{const g=await new GLTFLoader().setDRACOLoader(draco).loadAsync('./assets/hoshino.glb',e=>progress(e.total?`舞台准备中 · ${Math.round(e.loaded/e.total*100)}%`:'舞台准备中…'));this.model=g.scene;this.scene.add(g.scene);const characters=[];g.scene.traverse(o=>{if(!o.isMesh)return;if(o.userData.viewerGroup==='venue')o.visible=false;if(o.userData.viewerGroup==='character')characters.push(o);o.material=o.material.clone();if(o.material.transparent)o.material.depthWrite=false;this.materials.push(o.material);});this.scene.updateMatrixWorld(true);characters.forEach(o=>this.pivot.attach(o));this.ready=true;}finally{draco.dispose();}}
 shot(index,instant=false){this.index=index;const [p,t]=shots[index];const target=new THREE.Vector3(...t),position=new THREE.Vector3(...p);if(innerWidth<800)position.sub(target).multiplyScalar(1.28).add(target);this.transition={from:this.camera.position.clone(),fromT:this.controls.target.clone(),to:position,toT:target,start:performance.now()};if(instant||this.reduced){this.camera.position.copy(position);this.controls.target.copy(target);this.transition=null;this.camera.lookAt(target);}this.controls.update();}
 mood(name){const c=palettes[name]||palettes.sakura;this.targetTint.set(name==='night'?'#7982a4':name==='aurora'?'#d1dbff':name==='gold'?'#fff0da':'#fff1fa');this.beams.forEach((b,i)=>b.material.color.set(c[i%2]));if(this.particles)this.particles.material.color.set(c[0]);}
 cheer(color){this.particles.material.color.set(color);this.sticks.forEach(s=>s.material.color.set(color));}
 decorate(){for(let i=0;i<4;i++){const material=new THREE.MeshBasicMaterial({color:'#ff81bb',transparent:true,opacity:.028,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide});const beam=new THREE.Mesh(new THREE.ConeGeometry(.75,5,24,1,true),material);beam.position.set((i-1.5)*1.3,3.6,-1.3);beam.rotation.z=(i-1.5)*.22;this.scene.add(beam);this.beams.push(beam);}const positions=new Float32Array(220*3);for(let i=0;i<220;i++){positions[i*3]=(Math.random()-.5)*9;positions[i*3+1]=Math.random()*6;positions[i*3+2]=(Math.random()-.5)*5;}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));this.particles=new THREE.Points(geometry,new THREE.PointsMaterial({color:'#ffb3dc',size:.019,transparent:true,opacity:.6,depthWrite:false,blending:THREE.AdditiveBlending}));this.scene.add(this.particles);this.sticks=[];for(let i=0;i<35;i++){const s=new THREE.Mesh(new THREE.CapsuleGeometry(.012,.16,2,4),new THREE.MeshBasicMaterial({color:i%3?'#ff7abf':'#b39aff'}));s.position.set((i-17)*.18,.25+Math.random()*.3,2+Math.random());s.rotation.z=(Math.random()-.5)*.8;this.scene.add(s);this.sticks.push(s);}}
 frame(now){const dt=Math.min((now-(this.last||now))/1000,.05);this.last=now;if(document.hidden)return;this.frames++;if(this.transition){const a=this.transition;let k=this.reduced?1:Math.min(1,(now-a.start)/1800);k=k<.5?4*k*k*k:1-Math.pow(-2*k+2,3)/2;this.camera.position.lerpVectors(a.from,a.to,k);this.controls.target.lerpVectors(a.fromT,a.toT,k);this.camera.lookAt(this.controls.target);if(k>=1)this.transition=null;}if(this.controls.enabled)this.controls.update();this.tint.lerp(this.targetTint,this.reduced?1:Math.min(1,dt*2));this.materials.forEach(m=>{if(m.emissive)m.emissive.copy(this.tint);});if(this.motion&&!this.reduced){this.time+=dt;this.pivot.rotation.z=Math.sin(this.time*.85)*.008;this.particles.rotation.y=this.time*.015;this.beams.forEach((b,i)=>b.rotation.z=(i-1.5)*.22+Math.sin(this.time*.35+i)*.13);this.sticks.forEach((s,i)=>s.rotation.z=Math.sin(this.time*1.5+i)*.28);}else{this.pivot.rotation.set(0,0,0);}this.renderer.render(this.scene,this.camera);}
}
